version: '3.8'

services:
  dart-bot:
    image: bakeapple/dart-bot:latest
    container_name: dart-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
      - AUTHORIZED_USERS=AUTHORIZED_USERS_ID
    # Optional: Mount logs directory
    volumes:
      - type: bind
        source: /dart-bot/logs
        target: /app/logs
        bind:
          create_host_path: true
    # Optional: If you need to expose port for webhooks
    # ports:
    #   - "8080:8080"
    # Optional: Add health check
    healthcheck:
      test: [ "CMD", "ps", "aux", "|", "grep", "dart_bot" ]
      interval: 30s
      timeout: 10s
      retries: 3
